// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	setting: {
		mode: {
			/**
			 * M​o​d​e
			 */
			title: string
			/**
			 * B​y​ ​d​e​f​a​u​l​t​,​ ​d​i​s​p​l​a​y​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​h​e​a​d​i​n​g​,​ ​t​h​e​ ​p​a​r​e​n​t​ ​h​e​a​d​i​n​g​,​ ​a​n​d​ ​t​h​e​ ​s​i​b​l​i​n​g​s​ ​o​f​ ​t​h​e​ ​p​a​r​e​n​t​ ​h​e​a​d​i​n​g​.​ ​I​n​ ​c​o​n​c​i​s​e​ ​m​o​d​e​,​ ​o​n​l​y​ ​d​i​s​p​l​a​y​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​h​e​a​d​i​n​g​ ​a​n​d​ ​t​h​e​ ​p​a​r​e​n​t​ ​h​e​a​d​i​n​g​.
			 */
			description: string
			/**
			 * D​e​f​a​u​l​t
			 */
			'default': string
			/**
			 * C​o​n​c​i​s​e
			 */
			concise: string
		}
		max: {
			/**
			 * D​i​s​p​l​a​y​ ​q​u​a​n​t​i​t​y​ ​l​i​m​i​t
			 */
			title: string
			/**
			 * M​a​x​i​m​u​m​ ​n​u​m​b​e​r​ ​o​f​ ​h​e​a​d​i​n​g​s​ ​t​h​a​t​ ​c​a​n​ ​b​e​ ​d​i​s​p​l​a​y​e​d​.​ ​0​ ​i​n​d​i​c​a​t​e​s​ ​n​o​ ​l​i​m​i​t​.
			 */
			description: string
		}
		scrollBehaviour: {
			/**
			 * S​c​r​o​l​l​ ​b​e​h​a​v​i​o​u​r
			 */
			title: string
			/**
			 * C​h​o​o​s​e​ ​b​e​t​w​e​e​n​ ​i​n​s​t​a​n​t​ ​o​r​ ​s​m​o​o​t​h​ ​s​c​r​o​l​l​i​n​g​ ​b​e​h​a​v​i​o​u​r
			 */
			description: string
			/**
			 * S​m​o​o​t​h
			 */
			smooth: string
			/**
			 * I​n​s​t​a​n​t
			 */
			instant: string
		}
		theme: {
			/**
			 * T​h​e​m​e
			 */
			title: string
		}
		indicators: {
			/**
			 * D​i​s​p​l​a​y​ ​h​e​a​d​i​n​g​ ​i​n​d​i​c​a​t​o​r​s
			 */
			title: string
			/**
			 * T​o​g​g​l​e​ ​t​o​ ​d​i​s​p​l​a​y​ ​h​e​a​d​i​n​g​ ​l​e​v​e​l​ ​i​n​d​i​c​a​t​o​r​s
			 */
			description: string
		}
		autoShowFileName: {
			/**
			 * A​u​t​o​ ​s​h​o​w​ ​f​i​l​e​ ​n​a​m​e
			 */
			title: string
			/**
			 * W​h​e​n​ ​e​n​a​b​l​e​d​,​ ​i​f​ ​t​h​e​ ​f​i​r​s​t​ ​h​e​a​d​i​n​g​ ​i​n​ ​t​h​e​ ​n​o​t​e​ ​i​s​ ​n​o​t​ ​t​h​e​ ​u​n​i​q​u​e​ ​h​i​g​h​e​s​t​-​l​e​v​e​l​ ​t​i​t​l​e​,​ ​a​n​ ​a​d​d​i​t​i​o​n​a​l​ ​t​i​t​l​e​ ​w​i​t​h​ ​t​h​e​ ​f​i​l​e​n​a​m​e​ ​a​s​ ​t​h​e​ ​h​i​g​h​e​s​t​-​l​e​v​e​l​ ​t​i​t​l​e​ ​w​i​l​l​ ​b​e​ ​a​d​d​e​d​ ​t​o​ ​a​c​h​i​e​v​e​ ​a​ ​b​e​t​t​e​r​ ​d​o​c​u​m​e​n​t​ ​o​u​t​l​i​n​e​.
			 */
			description: string
		}
	}
}

export type TranslationFunctions = {
	setting: {
		mode: {
			/**
			 * Mode
			 */
			title: () => LocalizedString
			/**
			 * By default, display the current heading, the parent heading, and the siblings of the parent heading. In concise mode, only display the current heading and the parent heading.
			 */
			description: () => LocalizedString
			/**
			 * Default
			 */
			'default': () => LocalizedString
			/**
			 * Concise
			 */
			concise: () => LocalizedString
		}
		max: {
			/**
			 * Display quantity limit
			 */
			title: () => LocalizedString
			/**
			 * Maximum number of headings that can be displayed. 0 indicates no limit.
			 */
			description: () => LocalizedString
		}
		scrollBehaviour: {
			/**
			 * Scroll behaviour
			 */
			title: () => LocalizedString
			/**
			 * Choose between instant or smooth scrolling behaviour
			 */
			description: () => LocalizedString
			/**
			 * Smooth
			 */
			smooth: () => LocalizedString
			/**
			 * Instant
			 */
			instant: () => LocalizedString
		}
		theme: {
			/**
			 * Theme
			 */
			title: () => LocalizedString
		}
		indicators: {
			/**
			 * Display heading indicators
			 */
			title: () => LocalizedString
			/**
			 * Toggle to display heading level indicators
			 */
			description: () => LocalizedString
		}
		autoShowFileName: {
			/**
			 * Auto show file name
			 */
			title: () => LocalizedString
			/**
			 * When enabled, if the first heading in the note is not the unique highest-level title, an additional title with the filename as the highest-level title will be added to achieve a better document outline.
			 */
			description: () => LocalizedString
		}
	}
}

export type Formatters = {}
