// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n';

export type BaseTranslation = BaseTranslationType;
export type BaseLocale = 'en';

export type Locales = 'en' | 'zh';

export type Translation = RootTranslation;

export type Translations = RootTranslation;

type RootTranslation = {
  setting: {
    mode: {
      /**
       * M​o​d​e
       */
      title: string;
      /**
       * B​y​ ​d​e​f​a​u​l​t​,​ ​d​i​s​p​l​a​y​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​h​e​a​d​i​n​g​,​ ​t​h​e​ ​p​a​r​e​n​t​ ​h​e​a​d​i​n​g​,​ ​a​n​d​ ​t​h​e​ ​s​i​b​l​i​n​g​s​ ​o​f​ ​t​h​e​ ​p​a​r​e​n​t​ ​h​e​a​d​i​n​g​.​ ​I​n​ ​c​o​n​c​i​s​e​ ​m​o​d​e​,​ ​o​n​l​y​ ​d​i​s​p​l​a​y​ ​t​h​e​ ​c​u​r​r​e​n​t​ ​h​e​a​d​i​n​g​ ​a​n​d​ ​t​h​e​ ​p​a​r​e​n​t​ ​h​e​a​d​i​n​g​.
       */
      description: string;
      /**
       * D​e​f​a​u​l​t
       */
      default: string;
      /**
       * C​o​n​c​i​s​e
       */
      concise: string;
    };
    max: {
      /**
       * D​i​s​p​l​a​y​ ​q​u​a​n​t​i​t​y​ ​l​i​m​i​t
       */
      title: string;
      /**
       * M​a​x​i​m​u​m​ ​n​u​m​b​e​r​ ​o​f​ ​h​e​a​d​i​n​g​s​ ​t​h​a​t​ ​c​a​n​ ​b​e​ ​d​i​s​p​l​a​y​e​d​.​ ​0​ ​i​n​d​i​c​a​t​e​s​ ​n​o​ ​l​i​m​i​t​.
       */
      description: string;
    };
    scrollBehaviour: {
      /**
       * S​c​r​o​l​l​ ​B​e​h​a​v​i​o​u​r
       */
      title: string;
      /**
       * C​h​o​o​s​e​ ​b​e​t​w​e​e​n​ ​i​n​s​t​a​n​t​ ​o​r​ ​s​m​o​o​t​h​ ​s​c​r​o​l​l​i​n​g​ ​b​e​h​a​v​i​o​u​r
       */
      description: string;
      /**
       * A​u​t​o
       */
      auto: string;
      /**
       * S​m​o​o​t​h
       */
      smooth: string;
      /**
       * I​n​s​t​a​n​t
       */
      instant: string;
    };
  };
};

export type TranslationFunctions = {
  setting: {
    mode: {
      /**
       * Mode
       */
      title: () => LocalizedString;
      /**
       * By default, display the current heading, the parent heading, and the siblings of the parent heading. In concise mode, only display the current heading and the parent heading.
       */
      description: () => LocalizedString;
      /**
       * Default
       */
      default: () => LocalizedString;
      /**
       * Concise
       */
      concise: () => LocalizedString;
    };
    max: {
      /**
       * Display quantity limit
       */
      title: () => LocalizedString;
      /**
       * Maximum number of headings that can be displayed. 0 indicates no limit.
       */
      description: () => LocalizedString;
    };
    scrollBehaviour: {
      /**
       * Scroll Behaviour
       */
      title: () => LocalizedString;
      /**
       * Choose between instant or smooth scrolling behaviour
       */
      description: () => LocalizedString;
      /**
       * Auto
       */
      auto: () => LocalizedString;
      /**
       * Smooth
       */
      smooth: () => LocalizedString;
      /**
       * Instant
       */
      instant: () => LocalizedString;
    };
  };
};

export type Formatters = {};
